---
title: "Manipulating the graph object"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Manipulating-the-graph-object}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>",
  eval = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE
)

```

```{r gt_tables, include = FALSE, eval = TRUE, file='create_tables.R'}
```

```{=html}
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```
```{=html}
<style type="text/css">
pre {
    border-style: hidden;
}
</style>
```



# Manipulating the graph object {#manipulate}

Once you have a network object, you will want to explore it and access
parts of it or extract info from it.

Here is a table with some of the functions you'll use all the time in
any SNA project.

```{r table_manipulate, echo = FALSE, eval = TRUE}
table_manipulate
```

