
# bipartite network
# repeat several times, so allow for accidental random quirks that would be missed otherwise
g_i_b_d <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = TRUE)
g_i_b_u <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = FALSE)
g_n_b_d <- snafun::to_network(g_i_b_d)
g_n_b_u <- snafun::to_network(g_i_b_u)
g_m_b_d <- snafun::to_matrix(g_i_b_d)
g_m_b_u <- snafun::to_matrix(g_i_b_u)
den_b_d <- sna::gden(g_n_b_d, mode = "twomode")
den_b_u <- sna::gden(g_n_b_u, mode = "twomode")
expect_equal(g_density(g_i_b_d), den_b_d/2)
expect_equal(g_density(g_n_b_d), den_b_d/2)
expect_equal(g_density(g_m_b_d), den_b_d/2)
expect_equal(g_density(g_i_b_u), den_b_u/2)
expect_equal(g_density(g_n_b_u), den_b_u/2)
expect_equal(g_density(g_m_b_u), den_b_u/2)

g_i_b_d <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = TRUE)
g_i_b_u <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = FALSE)
g_n_b_d <- snafun::to_network(g_i_b_d)
g_n_b_u <- snafun::to_network(g_i_b_u)
g_m_b_d <- snafun::to_matrix(g_i_b_d)
g_m_b_u <- snafun::to_matrix(g_i_b_u)
den_b_d <- sna::gden(g_n_b_d, mode = "twomode")
den_b_u <- sna::gden(g_n_b_u, mode = "twomode")
expect_equal(g_density(g_i_b_d), den_b_d/2)
expect_equal(g_density(g_n_b_d), den_b_d/2)
expect_equal(g_density(g_m_b_d), den_b_d/2)
expect_equal(g_density(g_i_b_u), den_b_u/2)
expect_equal(g_density(g_n_b_u), den_b_u/2)
expect_equal(g_density(g_m_b_u), den_b_u/2)

g_i_b_d <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = TRUE)
g_i_b_u <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = FALSE)
g_n_b_d <- snafun::to_network(g_i_b_d)
g_n_b_u <- snafun::to_network(g_i_b_u)
g_m_b_d <- snafun::to_matrix(g_i_b_d)
g_m_b_u <- snafun::to_matrix(g_i_b_u)
den_b_d <- sna::gden(g_n_b_d, mode = "twomode")
den_b_u <- sna::gden(g_n_b_u, mode = "twomode")
expect_equal(g_density(g_i_b_d), den_b_d/2)
expect_equal(g_density(g_n_b_d), den_b_d/2)
expect_equal(g_density(g_m_b_d), den_b_d/2)
expect_equal(g_density(g_i_b_u), den_b_u/2)
expect_equal(g_density(g_n_b_u), den_b_u/2)
expect_equal(g_density(g_m_b_u), den_b_u/2)

g_i_b_d <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = TRUE)
g_i_b_u <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = FALSE)
g_n_b_d <- snafun::to_network(g_i_b_d)
g_n_b_u <- snafun::to_network(g_i_b_u)
g_m_b_d <- snafun::to_matrix(g_i_b_d)
g_m_b_u <- snafun::to_matrix(g_i_b_u)
den_b_d <- sna::gden(g_n_b_d, mode = "twomode")
den_b_u <- sna::gden(g_n_b_u, mode = "twomode")
expect_equal(g_density(g_i_b_d), den_b_d/2)
expect_equal(g_density(g_n_b_d), den_b_d/2)
expect_equal(g_density(g_m_b_d), den_b_d/2)
expect_equal(g_density(g_i_b_u), den_b_u/2)
expect_equal(g_density(g_n_b_u), den_b_u/2)
expect_equal(g_density(g_m_b_u), den_b_u/2)

g_i_b_d <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = TRUE)
g_i_b_u <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = FALSE)
g_n_b_d <- snafun::to_network(g_i_b_d)
g_n_b_u <- snafun::to_network(g_i_b_u)
g_m_b_d <- snafun::to_matrix(g_i_b_d)
g_m_b_u <- snafun::to_matrix(g_i_b_u)
den_b_d <- sna::gden(g_n_b_d, mode = "twomode")
den_b_u <- sna::gden(g_n_b_u, mode = "twomode")
expect_equal(g_density(g_i_b_d), den_b_d/2)
expect_equal(g_density(g_n_b_d), den_b_d/2)
expect_equal(g_density(g_m_b_d), den_b_d/2)
expect_equal(g_density(g_i_b_u), den_b_u/2)
expect_equal(g_density(g_n_b_u), den_b_u/2)
expect_equal(g_density(g_m_b_u), den_b_u/2)

g_i_b_d <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = TRUE)
g_i_b_u <- snafun::create_bipartite(10, 6, "gnp", p = .15, directed = FALSE)
g_n_b_d <- snafun::to_network(g_i_b_d)
g_n_b_u <- snafun::to_network(g_i_b_u)
g_m_b_d <- snafun::to_matrix(g_i_b_d)
g_m_b_u <- snafun::to_matrix(g_i_b_u)
den_b_d <- sna::gden(g_n_b_d, mode = "twomode")
den_b_u <- sna::gden(g_n_b_u, mode = "twomode")
expect_equal(g_density(g_i_b_d), den_b_d/2)
expect_equal(g_density(g_n_b_d), den_b_d/2)
expect_equal(g_density(g_m_b_d), den_b_d/2)
expect_equal(g_density(g_i_b_u), den_b_u/2)
expect_equal(g_density(g_n_b_u), den_b_u/2)
expect_equal(g_density(g_m_b_u), den_b_u/2)






# random graph
g_i_d <- snafun::create_random_graph(10, "gnp", p = .15, directed = TRUE)
g_i_u <- snafun::create_random_graph(10, "gnp", p = .15, directed = FALSE)
g_n_d <- snafun::to_network(g_i_d)
g_n_u <- snafun::to_network(g_i_u)
g_m_d <- snafun::to_matrix(g_i_d)
g_m_u <- snafun::to_matrix(g_i_u)
den_d <- sna::gden(g_n_d)
den_u <- sna::gden(g_n_u)
den_d_l <- sna::gden(g_n_d, diag = TRUE)
den_u_l <- sna::gden(g_n_u, diag = TRUE)
expect_equal(g_density(g_i_d), den_d)
expect_equal(g_density(g_n_d), den_d)
expect_equal(g_density(g_m_d), den_d)
expect_equal(g_density(g_i_u), den_u)
expect_equal(g_density(g_n_u), den_u)
expect_equal(g_density(g_m_u), den_u)
expect_equal(g_density(g_i_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_n_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_m_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_i_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_n_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_m_u, loops = TRUE), den_u_l)

g_i_d <- snafun::create_random_graph(10, "gnp", p = .15, directed = TRUE)
g_i_u <- snafun::create_random_graph(10, "gnp", p = .15, directed = FALSE)
g_n_d <- snafun::to_network(g_i_d)
g_n_u <- snafun::to_network(g_i_u)
g_m_d <- snafun::to_matrix(g_i_d)
g_m_u <- snafun::to_matrix(g_i_u)
den_d <- sna::gden(g_n_d)
den_u <- sna::gden(g_n_u)
den_d_l <- sna::gden(g_n_d, diag = TRUE)
den_u_l <- sna::gden(g_n_u, diag = TRUE)
expect_equal(g_density(g_i_d), den_d)
expect_equal(g_density(g_n_d), den_d)
expect_equal(g_density(g_m_d), den_d)
expect_equal(g_density(g_i_u), den_u)
expect_equal(g_density(g_n_u), den_u)
expect_equal(g_density(g_m_u), den_u)
expect_equal(g_density(g_i_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_n_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_m_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_i_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_n_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_m_u, loops = TRUE), den_u_l)

g_i_d <- snafun::create_random_graph(10, "gnp", p = .15, directed = TRUE)
g_i_u <- snafun::create_random_graph(10, "gnp", p = .15, directed = FALSE)
g_n_d <- snafun::to_network(g_i_d)
g_n_u <- snafun::to_network(g_i_u)
g_m_d <- snafun::to_matrix(g_i_d)
g_m_u <- snafun::to_matrix(g_i_u)
den_d <- sna::gden(g_n_d)
den_u <- sna::gden(g_n_u)
den_d_l <- sna::gden(g_n_d, diag = TRUE)
den_u_l <- sna::gden(g_n_u, diag = TRUE)
expect_equal(g_density(g_i_d), den_d)
expect_equal(g_density(g_n_d), den_d)
expect_equal(g_density(g_m_d), den_d)
expect_equal(g_density(g_i_u), den_u)
expect_equal(g_density(g_n_u), den_u)
expect_equal(g_density(g_m_u), den_u)
expect_equal(g_density(g_i_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_n_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_m_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_i_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_n_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_m_u, loops = TRUE), den_u_l)

g_i_d <- snafun::create_random_graph(10, "gnp", p = .15, directed = TRUE)
g_i_u <- snafun::create_random_graph(10, "gnp", p = .15, directed = FALSE)
g_n_d <- snafun::to_network(g_i_d)
g_n_u <- snafun::to_network(g_i_u)
g_m_d <- snafun::to_matrix(g_i_d)
g_m_u <- snafun::to_matrix(g_i_u)
den_d <- sna::gden(g_n_d)
den_u <- sna::gden(g_n_u)
den_d_l <- sna::gden(g_n_d, diag = TRUE)
den_u_l <- sna::gden(g_n_u, diag = TRUE)
expect_equal(g_density(g_i_d), den_d)
expect_equal(g_density(g_n_d), den_d)
expect_equal(g_density(g_m_d), den_d)
expect_equal(g_density(g_i_u), den_u)
expect_equal(g_density(g_n_u), den_u)
expect_equal(g_density(g_m_u), den_u)
expect_equal(g_density(g_i_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_n_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_m_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_i_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_n_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_m_u, loops = TRUE), den_u_l)

g_i_d <- snafun::create_random_graph(10, "gnp", p = .15, directed = TRUE)
g_i_u <- snafun::create_random_graph(10, "gnp", p = .15, directed = FALSE)
g_n_d <- snafun::to_network(g_i_d)
g_n_u <- snafun::to_network(g_i_u)
g_m_d <- snafun::to_matrix(g_i_d)
g_m_u <- snafun::to_matrix(g_i_u)
den_d <- sna::gden(g_n_d)
den_u <- sna::gden(g_n_u)
den_d_l <- sna::gden(g_n_d, diag = TRUE)
den_u_l <- sna::gden(g_n_u, diag = TRUE)
expect_equal(g_density(g_i_d), den_d)
expect_equal(g_density(g_n_d), den_d)
expect_equal(g_density(g_m_d), den_d)
expect_equal(g_density(g_i_u), den_u)
expect_equal(g_density(g_n_u), den_u)
expect_equal(g_density(g_m_u), den_u)
expect_equal(g_density(g_i_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_n_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_m_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_i_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_n_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_m_u, loops = TRUE), den_u_l)

g_i_d <- snafun::create_random_graph(10, "gnp", p = .15, directed = TRUE)
g_i_u <- snafun::create_random_graph(10, "gnp", p = .15, directed = FALSE)
g_n_d <- snafun::to_network(g_i_d)
g_n_u <- snafun::to_network(g_i_u)
g_m_d <- snafun::to_matrix(g_i_d)
g_m_u <- snafun::to_matrix(g_i_u)
den_d <- sna::gden(g_n_d)
den_u <- sna::gden(g_n_u)
den_d_l <- sna::gden(g_n_d, diag = TRUE)
den_u_l <- sna::gden(g_n_u, diag = TRUE)
expect_equal(g_density(g_i_d), den_d)
expect_equal(g_density(g_n_d), den_d)
expect_equal(g_density(g_m_d), den_d)
expect_equal(g_density(g_i_u), den_u)
expect_equal(g_density(g_n_u), den_u)
expect_equal(g_density(g_m_u), den_u)
expect_equal(g_density(g_i_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_n_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_m_d, loops = TRUE), den_d_l)
expect_equal(g_density(g_i_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_n_u, loops = TRUE), den_u_l)
expect_equal(g_density(g_m_u, loops = TRUE), den_u_l)


# network with density = 1
full_m <- matrix(1, ncol = 10, nrow = 10)
full_i_d <- snafun::to_igraph(full_m)
full_i_u <- snafun::to_igraph(full_m)
full_n_d <- snafun::to_network(full_i_d)
full_n_u <- snafun::to_network(full_i_u)
full_m_d <- snafun::to_matrix(full_i_d)
full_m_u <- snafun::to_matrix(full_i_u)
expect_true(g_density(full_i_d) == 1)
expect_true(g_density(full_i_u) == 1)
expect_true(g_density(full_n_d) == 1)
expect_true(g_density(full_n_u) == 1)
expect_true(g_density(full_m_d) == 1)
expect_true(g_density(full_m_u) == 1)
expect_true(g_density(full_i_d, loops = TRUE) == 1)
expect_true(g_density(full_i_u, loops = TRUE) == 1)
expect_true(g_density(full_n_d, loops = TRUE) == 1)
expect_true(g_density(full_n_u, loops = TRUE) == 1)
expect_true(g_density(full_m_d, loops = TRUE) == 1)
expect_true(g_density(full_m_u, loops = TRUE) == 1)

# only 1 vertex
g <- snafun::create_empty_graph(1, directed = TRUE)
g <- igraph::add_edges(g, c(1, 1))
expect_true(is.nan(g_density(g)))
expect_equal(g_density(g, loops = TRUE), 1)
g <- snafun::create_empty_graph(1, directed = FALSE)
g <- igraph::add_edges(g, c(1, 1))
expect_true(is.nan(g_density(g)))
expect_equal(g_density(g, loops = TRUE), 1)


# empty graph
g <- snafun::create_empty_graph(0, directed = TRUE)
expect_true(is.nan(g_density(g)))
expect_true(is.nan(g_density(g, loops = TRUE)))

# error
g <- snafun::create_bipartite(5, 6, "gnp", p = .15)
expect_error(g_density(g, loops = TRUE))
expect_error(g_density(snafun::to_network(g), loops = TRUE))
expect_error(g_density(snafun::to_matrix(g), loops = TRUE))


