
#' Fix intermediate CUG input
#' 
#' Fix the intermediate input from sna::cug.test
#' 
#' This function makes the \link[sna]{cug.test} useable for \code{snafun}. 
#' The cug.test function generates a series of networks in a specific way. 
#' This function converts that data format into an object of class \code{igraph}, 
#' which can then be handled by (almost) any function in \code{snafun} or 
#' \code{igraph} or other code that works with \code{igraph} objects.
#' 
#' This does slow down the computations in cug.test a little, but the added 
#' flexibility is a huge gain.
#' 
#' Make sure to set correctly whether the actual graph is directed or not.
#'
#' @param el the input generated by a single run of \code{sna::cug.test}
#' @param directed logical, is the graph directed or not?
#'
#' @return object of class \code{igraph}
#' @export
fix_cug_input <- function(el, directed = TRUE) {
  if (nrow(el) != ncol(el)) { # edge list in matrix format
    n <- attr(el, "n")
    el <- el[, 1:2]
    actors <- unique(c(el[, 1], el[,2]))
    
    g <- igraph::graph_from_edgelist(el, directed = directed) |> 
      igraph::simplify()
    
    missing <- setdiff(1:n, igraph::V(g))
    if (length(missing) > 0) {
      g <- igraph::add_vertices(g, nv = length(missing))
    }
  } else {
    g <- snafun::to_igraph(el)
  }
  g 
}


