#' Quadratic Assignment Procedure correlation test
#'
#' Run a QAP correlation test between two networks or network-like matrices.
#'
#' This function provides a \pkg{snafun}-style interface to the classic QAP
#' correlation test. The two focal inputs, \code{x} and \code{y}, can each be
#' supplied as an \code{igraph} object, a \code{network} object, a square
#' adjacency matrix, or an edgelist \code{data.frame}. Optional control
#' matrices can be added to obtain a partial correlation.
#'
#' Internally, all supported inputs are converted to numeric one-mode matrices
#' of identical size. The observed statistic is then just the ordinary
#' correlation between the vectorized adjacency matrices after applying the
#' requested directed/undirected and diagonal conventions. For directed
#' analyses, all dyads are used, optionally including the diagonal. For
#' undirected analyses, the full symmetric adjacency matrix is vectorized as-is;
#' this keeps the interpretation close to the matrix representation students
#' actually work with when they call \code{cor(c(A), c(B))}. QAP replications
#' are generated by simultaneously permuting the rows and columns of \code{y}
#' while keeping \code{x} and any control matrices fixed. This matches the usual
#' interpretation of QAP as testing whether \code{y} is associated with
#' \code{x} beyond what would be expected under vertex relabeling.
#'
#' When \code{controls} are supplied, \code{stat_qap_cor()} reports a partial
#' correlation. Concretely, the vectorized values of \code{x} and \code{y} are
#' each residualized on the control matrices, after which the correlation
#' between the two residual vectors is computed. With \code{method = "spearman"}
#' the vectors are first converted to ranks and the residual correlation is then
#' calculated on those ranks.
#'
#' For directed networks, this observed statistic coincides with
#' \code{\link[sna]{gcor}} once the same diagonal choice is made. For undirected
#' networks without diagonal entries, it also coincides with
#' \code{\link[sna]{gcor}} because duplicate off-diagonal cells cancel out in the
#' correlation. When \code{diagonal = TRUE} for an undirected network,
#' \code{stat_qap_cor()} follows the full adjacency-matrix representation rather
#' than the triangle-only convention used by \pkg{sna}. The permutation test
#' itself is implemented directly in \pkg{snafun}, so it works naturally with
#' the graph classes used throughout the package.
#'
#' @param x First network or network-like object.
#' @param y Second network or network-like object.
#' @param controls Optional control matrix or list of control matrices. Each
#'   control must be supplied in one of the same formats as \code{x} and
#'   \code{y}.
#' @param method Correlation method. One of \code{"pearson"} or
#'   \code{"spearman"}.
#' @param reps Number of QAP permutations.
#' @param diagonal Logical scalar; should diagonal entries be included?
#' @param directed How should the input be interpreted? One of \code{"auto"},
#'   \code{"directed"}, or \code{"undirected"}. The default infers this from
#'   \code{x}.
#' @param alternative Alternative hypothesis. One of \code{"two.sided"},
#'   \code{"greater"}, or \code{"less"}.
#' @param seed Optional integer seed for reproducible permutations.
#'
#' @return An object of class \code{stat_qap_cor} containing the observed
#'   correlation, the permutation distribution, and empirical p-values. The
#'   returned object stores the proportions of replicated statistics that are
#'   strictly greater than, strictly less than, and numerically equal to the
#'   observed value as \code{p.greater}, \code{p.less}, and \code{p.equal}.
#' @family statistics functions
#' @export
#'
#' @examples
#' x <- snafun::create_manual_graph(A -- B, B -- C, C -- D)
#' y <- snafun::create_manual_graph(A -- B, B -- D, C -- D)
#'
#' stat_qap_cor(x, y, reps = 99)
#'
#' x_n <- snafun::to_network(x)
#' y_m <- snafun::to_matrix(y)
#' stat_qap_cor(x_n, y_m, reps = 49, directed = "undirected")
#'
#' z <- snafun::add_vertices(
#'   snafun::create_manual_graph(A -- C, B -- C),
#'   vertices = "D"
#' )
#' stat_qap_cor(x, y, controls = z, reps = 49)
#'
#' z2 <- snafun::add_vertices(
#'   snafun::create_manual_graph(A -- D, B -- D),
#'   vertices = "C"
#' )
#' stat_qap_cor(x, y, controls = list(z, z2), reps = 49)
#'
#' xm <- snafun::to_matrix(x)
#' ym <- snafun::to_matrix(y)
#' zm <- snafun::to_matrix(z)
#' stat_qap_cor(xm, ym, controls = zm, reps = 49, diagonal = TRUE)
stat_qap_cor <- function(x,
                         y,
                         controls = NULL,
                         method = c("pearson", "spearman"),
                         reps = 1000,
                         diagonal = FALSE,
                         directed = c("auto", "directed", "undirected"),
                         alternative = c("two.sided", "greater", "less"),
                         seed = NULL) {
  method <- method[[1]]
  directed <- directed[[1]]
  alternative <- alternative[[1]]

  if (!method %in% c("pearson", "spearman")) {
    stop("'method' should be either 'pearson' or 'spearman'")
  }
  if (!directed %in% c("auto", "directed", "undirected")) {
    stop("'directed' should be one of 'auto', 'directed', or 'undirected'")
  }
  if (!alternative %in% c("two.sided", "greater", "less")) {
    stop("'alternative' should be one of 'two.sided', 'greater', or 'less'")
  }
  if (!is.logical(diagonal) || length(diagonal) != 1L || is.na(diagonal)) {
    stop("'diagonal' should be either TRUE or FALSE")
  }
  if (length(reps) != 1L || is.na(reps) || reps < 1 || reps != as.integer(reps)) {
    stop("'reps' should be a single positive integer")
  }
  reps <- as.integer(reps)
  if (!is.null(seed) && (length(seed) != 1L || is.na(seed))) {
    stop("'seed' should be NULL or a single non-missing integer value")
  }

  seed_state <- stat_qap_cor_set_seed(seed = seed)
  if (is.function(seed_state$restore)) {
    on.exit(seed_state$restore(), add = TRUE)
  }

  x_matrix_raw <- stat_qap_cor_prepare_matrix(x = x, directed_override = NULL)
  directed_flag <- stat_qap_cor_resolve_direction(
    x = x_matrix_raw,
    directed = directed
  )
  x_matrix <- stat_qap_cor_prepare_matrix(x = x, directed_override = directed_flag)
  y_matrix <- stat_qap_cor_prepare_matrix(
    x = y,
    directed_override = directed_flag,
    reference = x_matrix
  )
  control_matrices <- stat_qap_cor_prepare_controls(
    controls = controls,
    directed_flag = directed_flag,
    reference = x_matrix
  )

  obs_stat <- stat_qap_cor_compute(
    x = x_matrix,
    y = y_matrix,
    controls = control_matrices,
    method = method,
    diagonal = diagonal,
    directed = directed_flag
  )

  rep_stats <- numeric(reps)
  for (rep_index in seq_len(reps)) {
    permuted_y <- stat_qap_cor_permute_matrix(y_matrix)
    rep_stats[[rep_index]] <- stat_qap_cor_compute(
      x = x_matrix,
      y = permuted_y,
      controls = control_matrices,
      method = method,
      diagonal = diagonal,
      directed = directed_flag
    )
  }

  valid_replicates <- !(is.na(rep_stats) | is.nan(rep_stats))
  p_values <- stat_qap_cor_empirical_p(
    obs_stat = obs_stat,
    rep_stats = rep_stats,
    alternative = alternative
  )

  out <- list(
    obs.stat = obs_stat,
    rep.stat = rep_stats,
    method = method,
    diagonal = diagonal,
    mode = if (directed_flag) "digraph" else "graph",
    alternative = alternative,
    reps = reps,
    valid.reps = sum(valid_replicates),
    p.value = p_values$p.value,
    p.greater = p_values$p.greater,
    p.less = p_values$p.less,
    p.equal = p_values$p.equal,
    controls.used = length(control_matrices),
    n = nrow(x_matrix),
    seed = seed,
    call = match.call()
  )
  class(out) <- "stat_qap_cor"
  out
}


#' Summarize a QAP correlation result
#'
#' Summarize the permutation distribution from \code{\link{stat_qap_cor}}.
#'
#' @param object Object returned by \code{\link{stat_qap_cor}}.
#' @param na.rm Logical scalar; should missing replicate statistics be removed
#'   before summarizing?
#' @param ... Ignored.
#'
#' @return An object of class \code{summary.stat_qap_cor}.
#' @export
summary.stat_qap_cor <- function(object, na.rm = TRUE, ...) {
  rep_values <- object$rep.stat
  if (isTRUE(na.rm)) {
    rep_values <- rep_values[!(is.na(rep_values) | is.nan(rep_values))]
  }

  null_summary <- if (length(rep_values) == 0L) {
    c(
      Min. = NA_real_,
      `1st Qu.` = NA_real_,
      Median = NA_real_,
      Mean = NA_real_,
      `3rd Qu.` = NA_real_,
      Max. = NA_real_
    )
  } else {
    summary(rep_values)
  }

  null_sd <- if (length(rep_values) <= 1L) {
    NA_real_
  } else {
    stats::sd(rep_values)
  }

  out <- list(
    obs.stat = object$obs.stat,
    rep.stat = object$rep.stat,
    method = object$method,
    diagonal = object$diagonal,
    mode = object$mode,
    alternative = object$alternative,
    reps = object$reps,
    valid.reps = object$valid.reps,
    p.value = object$p.value,
    p.greater = object$p.greater,
    p.less = object$p.less,
    p.equal = object$p.equal,
    controls.used = object$controls.used,
    n = object$n,
    seed = object$seed,
    call = object$call,
    null.summary = null_summary,
    null.sd = null_sd
  )
  class(out) <- "summary.stat_qap_cor"
  out
}


#' Print a summary of a QAP correlation result
#'
#' Print the object returned by \code{\link{summary.stat_qap_cor}}.
#'
#' @param x Object returned by \code{\link{summary.stat_qap_cor}}.
#' @param digits Number of significant digits to print.
#' @param ... Ignored.
#'
#' @return Invisibly returns \code{x}.
#' @export
print.summary.stat_qap_cor <- function(x, digits = 4, ...) {
  cat("\nSummary of QAP Correlation Test\n\n")
  cat("Correlation Method:", x$method, "\n")
  cat("Graph Type:", x$mode, "\n")
  cat("Diagonal Used:", x$diagonal, "\n")
  cat("Alternative:", x$alternative, "\n")
  cat("Controls:", x$controls.used, "\n")
  cat("Vertices:", x$n, "\n")
  cat("Permutations:", x$reps, "\n")
  cat("Valid replicate statistics:", x$valid.reps, "\n\n")
  cat("Observed Correlation:", format(signif(x$obs.stat, digits = digits)), "\n")
  cat("Pr(X>Obs):", format(signif(x$p.greater, digits = digits)), "\n")
  cat("Pr(X<Obs):", format(signif(x$p.less, digits = digits)), "\n")
  cat("Pr(X=Obs):", format(signif(x$p.equal, digits = digits)), "\n\n")
  cat("Null distribution summary:\n")
  print(signif(c(x$null.summary, `Std. Dev.` = x$null.sd), digits = digits))
  invisible(x)
}


#' Print a QAP correlation result
#'
#' Print a compact summary of a \code{stat_qap_cor} result.
#'
#' @param x Object returned by \code{\link{stat_qap_cor}}.
#' @param digits Number of significant digits to print.
#' @param ... Ignored.
#'
#' @return Invisibly returns \code{x}.
#' @export
print.stat_qap_cor <- function(x, digits = 4, ...) {
  cat("\nQuadratic Assignment Procedure Correlation Test\n\n")
  cat("Correlation Method:", x$method, "\n")
  cat("Graph Type:", x$mode, "\n")
  cat("Diagonal Used:", x$diagonal, "\n")
  cat("Alternative:", x$alternative, "\n")
  cat("Controls:", x$controls.used, "\n")
  cat("Vertices:", x$n, "\n")
  cat("Permutations:", x$reps, "\n")
  cat("Valid replicate statistics:", x$valid.reps, "\n\n")
  cat("Observed Correlation:", format(signif(x$obs.stat, digits = digits)), "\n")
  cat("Pr(X>Obs):", format(signif(x$p.greater, digits = digits)), "\n")
  cat("Pr(X<Obs):", format(signif(x$p.less, digits = digits)), "\n")
  cat("Pr(X=Obs):", format(signif(x$p.equal, digits = digits)), "\n\n")
  invisible(x)
}


#' Plot a QAP correlation result
#'
#' Plot the permutation distribution from \code{\link{stat_qap_cor}} and mark
#' the observed correlation with a vertical line.
#'
#' @param x Object returned by \code{\link{stat_qap_cor}}.
#' @param main Plot title.
#' @param sub Plot subtitle.
#' @param breaks Histogram break specification.
#' @param col Fill color for the histogram bars.
#' @param border Border color for the histogram bars.
#' @param observed_col Color of the observed-value reference line.
#' @param observed_lwd Line width of the observed-value reference line.
#' @param xlab X-axis label.
#' @param prob Logical scalar; should a density histogram be drawn?
#' @param ... Additional graphical arguments passed to
#'   \code{\link[graphics]{hist}}.
#'
#' @return Invisibly returns \code{x}.
#' @export
plot.stat_qap_cor <- function(x,
                              main = "QAP Correlation Test",
                              sub = paste("Permutations:", x$reps, "Alternative:", x$alternative),
                              breaks = "Sturges",
                              col = "grey85",
                              border = "white",
                              observed_col = "firebrick",
                              observed_lwd = 2,
                              xlab = "Permutation correlations",
                              prob = TRUE,
                              ...) {
  rep_values <- x$rep.stat[!(is.na(x$rep.stat) | is.nan(x$rep.stat))]
  if (length(rep_values) == 0L) {
    stop("There are no valid replicate statistics to plot")
  }

  graphics::hist(
    rep_values,
    breaks = breaks,
    col = col,
    border = border,
    prob = prob,
    main = main,
    sub = sub,
    xlab = xlab,
    ...
  )
  if (!(is.na(x$obs.stat) | is.nan(x$obs.stat))) {
    graphics::abline(v = x$obs.stat, col = observed_col, lwd = observed_lwd)
  }
  invisible(x)
}


#' Convert a supported graph-like input to a QAP-ready matrix
#'
#' @keywords internal
#' @noRd
stat_qap_cor_prepare_matrix <- function(x,
                                        directed_override = NULL,
                                        reference = NULL) {
  if (!inherits(x, "igraph") &&
      !inherits(x, "network") &&
      !is.matrix(x) &&
      !is.data.frame(x)) {
    stop(
      "All QAP inputs should be 'igraph' objects, 'network' objects, square matrices, or edgelist data.frames"
    )
  }

  if (inherits(x, "data.frame")) {
    mat <- snafun::to_matrix(x, directed = directed_override)
  } else {
    mat <- snafun::to_matrix(x)
  }

  if (!is.matrix(mat) || nrow(mat) != ncol(mat)) {
    stop("'stat_qap_cor()' is only defined for one-mode square matrices")
  }
  if (anyNA(mat)) {
    stop("Missing values are currently not supported in 'stat_qap_cor()'")
  }

  storage.mode(mat) <- "numeric"
  mat <- stat_qap_cor_standardize_dimnames(mat = mat)

  if (!is.null(reference)) {
    mat <- stat_qap_cor_align_to_reference(mat = mat, reference = reference)
  }

  if (!is.null(directed_override) && !isTRUE(directed_override)) {
    if (!isSymmetric(unname(mat), check.attributes = FALSE)) {
      stop(
        "Undirected QAP correlations require symmetric matrices. ",
        "Please supply symmetric data or set 'directed = \"directed\"'."
      )
    }
  }

  mat
}


#' Standardize matrix dimnames for QAP work
#'
#' @keywords internal
#' @noRd
stat_qap_cor_standardize_dimnames <- function(mat) {
  row_names <- rownames(mat)
  col_names <- colnames(mat)

  if (is.null(row_names) && is.null(col_names)) {
    labels <- as.character(seq_len(nrow(mat)))
    rownames(mat) <- labels
    colnames(mat) <- labels
    return(mat)
  }

  if (is.null(row_names) && !is.null(col_names)) {
    rownames(mat) <- col_names
    row_names <- col_names
  }
  if (!is.null(row_names) && is.null(col_names)) {
    colnames(mat) <- row_names
    col_names <- row_names
  }

  if (!identical(sort(row_names), sort(col_names))) {
    stop("Row and column names of a QAP matrix should refer to the same vertices")
  }

  if (!identical(row_names, col_names)) {
    mat <- mat[row_names, row_names, drop = FALSE]
  }

  mat
}


#' Align a QAP matrix to a reference ordering
#'
#' @keywords internal
#' @noRd
stat_qap_cor_align_to_reference <- function(mat, reference) {
  ref_names <- rownames(reference)
  mat_names <- rownames(mat)

  if (is.null(ref_names) || is.null(mat_names)) {
    if (nrow(mat) != nrow(reference)) {
      stop("All QAP inputs should have the same number of vertices")
    }
    rownames(mat) <- rownames(reference)
    colnames(mat) <- colnames(reference)
    return(mat)
  }

  if (!setequal(ref_names, mat_names)) {
    stop("All QAP inputs should refer to the same vertex set")
  }

  mat[ref_names, ref_names, drop = FALSE]
}


#' Normalize control inputs for QAP correlation
#'
#' @keywords internal
#' @noRd
stat_qap_cor_prepare_controls <- function(controls, directed_flag, reference) {
  if (is.null(controls)) {
    return(list())
  }

  control_list <- controls
  if (inherits(control_list, "igraph") ||
      inherits(control_list, "network") ||
      is.matrix(control_list) ||
      is.data.frame(control_list)) {
    control_list <- list(control_list)
  }

  lapply(
    control_list,
    function(one_control) {
      stat_qap_cor_prepare_matrix(
        x = one_control,
        directed_override = directed_flag,
        reference = reference
      )
    }
  )
}


#' Resolve the directedness setting for QAP correlation
#'
#' @keywords internal
#' @noRd
stat_qap_cor_resolve_direction <- function(x, directed) {
  if (identical(directed, "auto")) {
    return(!isSymmetric(unname(x), check.attributes = FALSE))
  }
  identical(directed, "directed")
}


#' Vectorize a matrix for QAP correlation
#'
#' @keywords internal
#' @noRd
stat_qap_cor_vectorize <- function(x, diagonal, directed) {
  selector <- matrix(TRUE, nrow = nrow(x), ncol = ncol(x))
  if (!diagonal) {
    diag(selector) <- FALSE
  }

  as.numeric(x[selector])
}


#' Compute an observed or permuted QAP correlation
#'
#' @keywords internal
#' @noRd
stat_qap_cor_compute <- function(x, y, controls, method, diagonal, directed) {
  x_vec <- stat_qap_cor_vectorize(x = x, diagonal = diagonal, directed = directed)
  y_vec <- stat_qap_cor_vectorize(x = y, diagonal = diagonal, directed = directed)
  z_mat <- stat_qap_cor_vectorize_controls(
    controls = controls,
    diagonal = diagonal,
    directed = directed
  )

  vectors <- stat_qap_cor_transform_vectors(
    x = x_vec,
    y = y_vec,
    z = z_mat,
    method = method
  )

  if (ncol(vectors$z) == 0L) {
    if (stats::sd(vectors$x) == 0 || stats::sd(vectors$y) == 0) {
      return(NA_real_)
    }
    return(stats::cor(vectors$x, vectors$y, method = "pearson"))
  }

  x_resid <- stat_qap_cor_residualize(y = vectors$x, x = vectors$z)
  y_resid <- stat_qap_cor_residualize(y = vectors$y, x = vectors$z)
  if (stats::sd(x_resid) == 0 || stats::sd(y_resid) == 0) {
    return(NA_real_)
  }
  stats::cor(x_resid, y_resid, method = "pearson")
}


#' Vectorize control matrices for QAP correlation
#'
#' @keywords internal
#' @noRd
stat_qap_cor_vectorize_controls <- function(controls, diagonal, directed) {
  if (length(controls) == 0L) {
    return(matrix(numeric(0), nrow = length(logical(0)), ncol = 0L))
  }

  columns <- lapply(
    controls,
    function(one_control) {
      stat_qap_cor_vectorize(
        x = one_control,
        diagonal = diagonal,
        directed = directed
      )
    }
  )

  out <- do.call(cbind, columns)
  if (is.null(dim(out))) {
    out <- matrix(out, ncol = 1L)
  }
  out
}


#' Apply the selected correlation scale to QAP vectors
#'
#' @keywords internal
#' @noRd
stat_qap_cor_transform_vectors <- function(x, y, z, method) {
  if (identical(method, "spearman")) {
    x <- rank(x, ties.method = "average")
    y <- rank(y, ties.method = "average")
    if (ncol(z) > 0L) {
      z <- apply(z, 2, rank, ties.method = "average")
      if (is.null(dim(z))) {
        z <- matrix(z, ncol = 1L)
      }
    }
  }

  list(x = x, y = y, z = z)
}


#' Residualize a numeric vector on a control matrix
#'
#' @keywords internal
#' @noRd
stat_qap_cor_residualize <- function(y, x) {
  if (ncol(x) == 0L) {
    return(y)
  }

  design <- cbind("(Intercept)" = 1, x)
  fit <- stats::lm.fit(x = design, y = y)
  fit$residuals
}


#' Permute a matrix by relabeling vertices
#'
#' @keywords internal
#' @noRd
stat_qap_cor_permute_matrix <- function(x) {
  permutation <- sample.int(nrow(x))
  x[permutation, permutation, drop = FALSE]
}


#' Compute empirical p-values for a QAP permutation distribution
#'
#' @keywords internal
#' @noRd
stat_qap_cor_empirical_p <- function(obs_stat, rep_stats, alternative) {
  valid <- !(is.na(rep_stats) | is.nan(rep_stats))
  if (is.na(obs_stat) || is.nan(obs_stat) || !any(valid)) {
    return(list(
      p.value = NA_real_,
      p.greater = NA_real_,
      p.less = NA_real_,
      p.equal = NA_real_
    ))
  }

  rep_values <- rep_stats[valid]
  tie_tolerance <- sqrt(.Machine$double.eps)
  is_equal <- abs(rep_values - obs_stat) <= tie_tolerance
  p_equal <- mean(is_equal)
  p_greater <- mean(rep_values > (obs_stat + tie_tolerance))
  p_less <- mean(rep_values < (obs_stat - tie_tolerance))
  p_greater_or_equal <- p_greater + p_equal
  p_less_or_equal <- p_less + p_equal
  p_value <- switch(
    alternative,
    two.sided = min(1, 2 * min(p_greater_or_equal, p_less_or_equal)),
    greater = p_greater_or_equal,
    less = p_less_or_equal
  )

  list(
    p.value = p_value,
    p.greater = p_greater,
    p.less = p_less,
    p.equal = p_equal
  )
}


#' Temporarily set the RNG seed for a QAP test
#'
#' @keywords internal
#' @noRd
stat_qap_cor_set_seed <- function(seed) {
  if (is.null(seed)) {
    return(list(restore = NULL))
  }

  had_seed <- exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
  old_seed <- if (had_seed) get(".Random.seed", envir = .GlobalEnv, inherits = FALSE) else NULL
  set.seed(as.integer(seed))

  restore <- function() {
    if (had_seed) {
      assign(".Random.seed", old_seed, envir = .GlobalEnv)
    } else if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) {
      rm(".Random.seed", envir = .GlobalEnv)
    }
  }

  list(restore = restore)
}
